# early_stopping:
#   _target_: pytorch_lightning.callbacks.EarlyStopping
#   monitor: val_loss
#   mode: min
#   min_delta: 0.001
#   patience: 10

model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: checkpoints
  filename: epoch_{epoch:03d}
  monitor: val_loss
  mode: min
  save_top_k: 1

lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: epoch